version: '3.8'

services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./database_data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - default