version: '3.8'

services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER}
    networks:
      - default
networks:
  default:
    name: ${NETWORK_NAME}
