version: '3.8'

services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER}
    networks:
      - default
  postgres:
    build:
      context: dockerfiles/postgres
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - default

networks:
  default:
    name: ${NETWORK_NAME}
